spring.application.name=backendbancoimagenes

spring.datasource.url=jdbc:mysql://localhost:3306/banco_imagenes?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=112358

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=tu_clave_secreta_segura_de_256_bits
jwt.expiration=86400000

